version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - SESSION_DRIVER=database
      - SESSION_DOMAIN=localhost
      - SESSION_SECURE_COOKIE=false
      - APP_URL=http://localhost:8000
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,localhost:5173,localhost:8000
    volumes:
      - app-volume:/var/www
      - ./docker/php/production.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    ports:
      - "80:80"
    volumes:
      - app-volume:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secure_root_password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secure_password}

volumes:
  app-volume:
