# Development environment overrides
# This file is used for local development only
services:
  app:
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    # For development, ensure the container user matches host user
    user: "1000:1000"

  nginx:
    ports:
      - "8000:80"

  db:
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"
